from fpdf import FPDF

pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()

# Titulo
pdf.set_font('Helvetica', 'B', 16)
pdf.cell(0, 10, 'Guia de Configuracion del Asistente IA', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.ln(5)

# 1. Requisitos de Instalacion
pdf.set_font('Helvetica', 'B', 14)
pdf.cell(0, 10, '1. Requisitos de Instalacion', new_x="LMARGIN", new_y="NEXT")
pdf.ln(2)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '1.1 Requisitos de Hardware', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '  - Procesador: Intel Core i5 o superior\n')
pdf.write(6, '  - Memoria RAM: 8 GB minimo, 16 GB recomendado\n')
pdf.write(6, '  - Almacenamiento: 20 GB de espacio libre\n')
pdf.write(6, '  - Conexion a Internet: Requerida para descarga inicial\n')
pdf.ln(3)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '1.2 Requisitos de Software', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '  - Sistema Operativo: Windows 10/11 o Linux Ubuntu 20.04+\n')
pdf.write(6, '  - .NET 8.0 Runtime\n')
pdf.write(6, '  - SQL Server 2019 o superior\n')
pdf.write(6, '  - Ollama instalado\n')
pdf.write(6, '  - Navegador web moderno (Chrome, Firefox, Edge)\n')
pdf.ln(3)

# 2. Instalacion Paso a Paso
pdf.add_page()
pdf.set_font('Helvetica', 'B', 14)
pdf.cell(0, 10, '2. Instalacion Paso a Paso', new_x="LMARGIN", new_y="NEXT")
pdf.ln(2)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '2.1 Descargar el Proyecto', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '1. Clonar el repositorio desde GitHub:\n')
pdf.set_font('Courier', '', 10)
pdf.write(5, 'git clone https://github.com/empresa/asistente-ia.git\n')
pdf.write(5, 'cd asistente-ia\n')
pdf.ln(2)
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '2. Restaurar dependencias:\n')
pdf.set_font('Courier', '', 10)
pdf.write(5, 'dotnet restore\n')
pdf.ln(3)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '2.2 Configurar Base de Datos', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '1. Crear la base de datos en SQL Server:\n')
pdf.set_font('Courier', '', 10)
pdf.write(5, 'CREATE DATABASE AsistenteIA;\n')
pdf.ln(2)
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '2. Ejecutar migraciones:\n')
pdf.set_font('Courier', '', 10)
pdf.write(5, 'dotnet ef database update\n')
pdf.ln(3)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '2.3 Configurar Ollama', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '1. Instalar Ollama desde https://ollama.ai\n')
pdf.write(6, '2. Descargar el modelo DeepSeek-R1:\n')
pdf.set_font('Courier', '', 10)
pdf.write(5, 'ollama pull deepseek-r1:7b\n')
pdf.ln(3)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '2.4 Configurar Variables de Entorno', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, 'Crear archivo .env con:\n')
pdf.set_font('Courier', '', 10)
pdf.write(5, 'ConnectionStrings__DefaultConnection=Server=localhost;Database=AsistenteIA;Trusted_Connection=True;\n')
pdf.write(5, 'Ollama__Url=http://localhost:11434\n')
pdf.write(5, 'Ollama__Modelo=deepseek-r1:7b\n')

# 3. Ejecutar la Aplicacion
pdf.add_page()
pdf.set_font('Helvetica', 'B', 14)
pdf.cell(0, 10, '3. Ejecutar la Aplicacion', new_x="LMARGIN", new_y="NEXT")
pdf.ln(2)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '3.1 Modo Desarrollo', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Courier', '', 10)
pdf.write(5, 'dotnet run --project Asistente.Web\n')
pdf.ln(3)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '3.2 Modo Produccion', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Courier', '', 10)
pdf.write(5, 'dotnet publish -c Release -o ./publish\n')
pdf.write(5, 'cd publish\n')
pdf.write(5, 'dotnet Asistente.Web.dll\n')

# 4. Configuracion Inicial
pdf.ln(5)
pdf.set_font('Helvetica', 'B', 14)
pdf.cell(0, 10, '4. Configuracion Inicial', new_x="LMARGIN", new_y="NEXT")
pdf.ln(2)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '4.1 Crear Usuario Administrador', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '  - Acceder a http://localhost:5000\n')
pdf.write(6, '  - Registrar usuario con rol "Administrador"\n')
pdf.write(6, '  - Configurar perfil y preferencias\n')
pdf.ln(3)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '4.2 Configurar Asistente', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '  - Ir a "Asistentes" en el menu\n')
pdf.write(6, '  - Crear nuevo asistente\n')
pdf.write(6, '  - Configurar prompt del sistema\n')
pdf.write(6, '  - Seleccionar modelo DeepSeek-R1\n')
pdf.write(6, '  - Guardar configuracion\n')

# 5. Solucion de Problemas
pdf.add_page()
pdf.set_font('Helvetica', 'B', 14)
pdf.cell(0, 10, '5. Solucion de Problemas', new_x="LMARGIN", new_y="NEXT")
pdf.ln(2)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '5.1 Error de Conexion a Ollama', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '  - Verificar que Ollama este ejecutandose: ollama list\n')
pdf.write(6, '  - Verificar URL en configuracion: http://localhost:11434\n')
pdf.write(6, '  - Reiniciar servicio Ollama\n')
pdf.ln(3)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '5.2 Error de Base de Datos', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '  - Verificar cadena de conexion\n')
pdf.write(6, '  - Verificar que SQL Server este ejecutandose\n')
pdf.write(6, '  - Ejecutar migraciones: dotnet ef database update\n')
pdf.ln(3)

pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, '5.3 Modelo No Disponible', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '  - Descargar modelo: ollama pull deepseek-r1:7b\n')
pdf.write(6, '  - Verificar espacio en disco: minimo 4 GB\n')
pdf.write(6, '  - Reiniciar Ollama\n')

# 6. Soporte y Contacto
pdf.ln(5)
pdf.set_font('Helvetica', 'B', 14)
pdf.cell(0, 10, '6. Soporte y Contacto', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.write(6, '  - Email: soporte@empresa.com\n')
pdf.write(6, '  - Documentacion: https://docs.empresa.com/asistente-ia\n')
pdf.write(6, '  - GitHub Issues: https://github.com/empresa/asistente-ia/issues\n')

# Guardar PDF
pdf.output('C:\\Users\\Raul\\Desktop\\AsistenteIA\\DocumentoPrueba_Configuracion.pdf')
print('PDF creado exitosamente: DocumentoPrueba_Configuracion.pdf')
